//module mana {
//	export module utils {
//		export class KeyboardDef extends egret.HashObject {
//
//			public static KC_NULL:number;
//			public static KC_0:number;
//			public static KC_1:number;
//			public static KC_2:number;
//			public static KC_3:number;
//			public static KC_4:number;
//			public static KC_5:number;
//			public static KC_6:number;
//			public static KC_7:number;
//			public static KC_8:number;
//			public static KC_9:number;
//			public static KC_A:number;
//			public static KC_B:number;
//			public static KC_C:number;
//			public static KC_D:number;
//			public static KC_E:number;
//			public static KC_F:number;
//			public static KC_G:number;
//			public static KC_H:number;
//			public static KC_I:number;
//			public static KC_J:number;
//			public static KC_K:number;
//			public static KC_L:number;
//			public static KC_M:number;
//			public static KC_N:number;
//			public static KC_O:number;
//			public static KC_P:number;
//			public static KC_Q:number;
//			public static KC_R:number;
//			public static KC_S:number;
//			public static KC_T:number;
//			public static KC_U:number;
//			public static KC_V:number;
//			public static KC_W:number;
//			public static KC_X:number;
//			public static KC_Y:number;
//			public static KC_Z:number;
//			public static KC_F1:number;
//			public static KC_F2:number;
//			public static KC_F3:number;
//			public static KC_F4:number;
//			public static KC_F5:number;
//			public static KC_F6:number;
//			public static KC_F7:number;
//			public static KC_F8:number;
//			public static KC_F9:number;
//			public static KC_F10:number;
//			public static KC_F11:number;
//			public static KC_F12:number;
//			public static KC_F13:number;
//			public static KC_F14:number;
//			public static KC_F15:number;
//			public static KC_BACKSPACE:number;
//			public static KC_TAB:number;
//			public static KC_ENTER:number;
//			public static KC_SHIFT:number;
//			public static KC_CONTROL:number;
//			public static KC_ESCAPE:number;
//			public static KC_SPACE:number;
//			public static KC_CAPS_LOCK:number;
//			public static KC_NUM_LOCK:number;
//			public static KC_SCROLL_LOCK:number;
//			public static KC_PAUSE:number;
//			public static KC_PAGE_UP:number;
//			public static KC_PAGE_DOWN:number;
//			public static KC_END:number;
//			public static KC_HOME:number;
//			public static KC_INSERT:number;
//			public static KC_DELETE:number;
//			public static KC_LEFT:number;
//			public static KC_UP:number;
//			public static KC_RIGHT:number;
//			public static KC_DOWN:number;
//			public static KC_WINDOWS:number;
//			public static KC_MENU:number;
//			public static ACTION_STATE_NORMAL:number;
//			public static ACTION_STATE_STOP:number;
//			public static ACTION_STATE_DISACCORD:number;
//		}
//	}
//}
//
//mana.utils.KeyboardDef.KC_NULL = -1;
//mana.utils.KeyboardDef.KC_0 = 48;
//mana.utils.KeyboardDef.KC_1 = 49;
//mana.utils.KeyboardDef.KC_2 = 50;
//mana.utils.KeyboardDef.KC_3 = 51;
//mana.utils.KeyboardDef.KC_4 = 52;
//mana.utils.KeyboardDef.KC_5 = 53;
//mana.utils.KeyboardDef.KC_6 = 54;
//mana.utils.KeyboardDef.KC_7 = 55;
//mana.utils.KeyboardDef.KC_8 = 56;
//mana.utils.KeyboardDef.KC_9 = 57;
//mana.utils.KeyboardDef.KC_A = 65;
//mana.utils.KeyboardDef.KC_B = 66;
//mana.utils.KeyboardDef.KC_C = 67;
//mana.utils.KeyboardDef.KC_D = 68;
//mana.utils.KeyboardDef.KC_E = 69;
//mana.utils.KeyboardDef.KC_F = 70;
//mana.utils.KeyboardDef.KC_G = 71;
//mana.utils.KeyboardDef.KC_H = 72;
//mana.utils.KeyboardDef.KC_I = 73;
//mana.utils.KeyboardDef.KC_J = 74;
//mana.utils.KeyboardDef.KC_K = 75;
//mana.utils.KeyboardDef.KC_L = 76;
//mana.utils.KeyboardDef.KC_M = 77;
//mana.utils.KeyboardDef.KC_N = 78;
//mana.utils.KeyboardDef.KC_O = 79;
//mana.utils.KeyboardDef.KC_P = 80;
//mana.utils.KeyboardDef.KC_Q = 81;
//mana.utils.KeyboardDef.KC_R = 82;
//mana.utils.KeyboardDef.KC_S = 83;
//mana.utils.KeyboardDef.KC_T = 84;
//mana.utils.KeyboardDef.KC_U = 85;
//mana.utils.KeyboardDef.KC_V = 86;
//mana.utils.KeyboardDef.KC_W = 87;
//mana.utils.KeyboardDef.KC_X = 88;
//mana.utils.KeyboardDef.KC_Y = 89;
//mana.utils.KeyboardDef.KC_Z = 90;
//mana.utils.KeyboardDef.KC_F1 = 112;
//mana.utils.KeyboardDef.KC_F2 = 113;
//mana.utils.KeyboardDef.KC_F3 = 114;
//mana.utils.KeyboardDef.KC_F4 = 115;
//mana.utils.KeyboardDef.KC_F5 = 116;
//mana.utils.KeyboardDef.KC_F6 = 117;
//mana.utils.KeyboardDef.KC_F7 = 118;
//mana.utils.KeyboardDef.KC_F8 = 119;
//mana.utils.KeyboardDef.KC_F9 = 120;
//mana.utils.KeyboardDef.KC_F10 = 121;
//mana.utils.KeyboardDef.KC_F11 = 122;
//mana.utils.KeyboardDef.KC_F12 = 123;
//mana.utils.KeyboardDef.KC_F13 = 124;
//mana.utils.KeyboardDef.KC_F14 = 125;
//mana.utils.KeyboardDef.KC_F15 = 126;
//mana.utils.KeyboardDef.KC_BACKSPACE = 8;
//mana.utils.KeyboardDef.KC_TAB = 9;
//mana.utils.KeyboardDef.KC_ENTER = 13;
//mana.utils.KeyboardDef.KC_SHIFT = 16;
//mana.utils.KeyboardDef.KC_CONTROL = 17;
//mana.utils.KeyboardDef.KC_ESCAPE = 27;
//mana.utils.KeyboardDef.KC_SPACE = 32;
//mana.utils.KeyboardDef.KC_CAPS_LOCK = 20;
//mana.utils.KeyboardDef.KC_NUM_LOCK = 144;
//mana.utils.KeyboardDef.KC_SCROLL_LOCK = 145;
//mana.utils.KeyboardDef.KC_PAUSE = 19;
//mana.utils.KeyboardDef.KC_PAGE_UP = 33;
//mana.utils.KeyboardDef.KC_PAGE_DOWN = 34;
//mana.utils.KeyboardDef.KC_END = 35;
//mana.utils.KeyboardDef.KC_HOME = 36;
//mana.utils.KeyboardDef.KC_INSERT = 45;
//mana.utils.KeyboardDef.KC_DELETE = 46;
//mana.utils.KeyboardDef.KC_LEFT = 37;
//mana.utils.KeyboardDef.KC_UP = 38;
//mana.utils.KeyboardDef.KC_RIGHT = 39;
//mana.utils.KeyboardDef.KC_DOWN = 40;
//mana.utils.KeyboardDef.KC_WINDOWS = 91;
//mana.utils.KeyboardDef.KC_MENU = 93;
//mana.utils.KeyboardDef.ACTION_STATE_NORMAL = 0;
//mana.utils.KeyboardDef.ACTION_STATE_STOP = 1;
//mana.utils.KeyboardDef.ACTION_STATE_DISACCORD = 2;
